### ISSUE TITLE
cbatch 参数识别错误不报错，以及不识别-N问题

### ISSUE THREAD

**Issue by Ashlee1994** [PKUHPC/CraneSched#128]
cbatch脚本中出现

1. #CBATCH --nodeNum参数，--nodeNum参数不是系统指定参数，但是cbatch提交作业不报错。
2. -N表示指定节点数量与--nodes同义，但是目前不支持，需要添加。

**Comment by June19980** [comment]
![Image](https://github.com/PKUHPC/Crane/assets/38131405/bbab9d61-02d1-4295-8d1c-c0998a87cc51)

2目前是支持的
