### ISSUE TITLE
作业添加priority属性，并对多因素综合调度算法进行测试

### ISSUE THREAD

**Issue by Ashlee1994** [PKUHPC/CraneSched#158]
1. 给作业添加priority属性，cqueue --format中%p显示作业的优先级。

2. 添加对多因素综合算法测试，比如控制5个作业的其他参数不变，只改变作业timelimit，这5个作业的优先级应该是timelimit越小，作业优先级越大。

  用控制变量法逐个测试多因素综合算法里面的其他因素，并附测试截图。

**Comment by Ashlee1994** [comment]
添加对多因素综合算法测试，比如控制5个作业的其他参数不变，只改变作业timelimit，这5个作业的优先级应该是timelimit越小，作业优先级越大。

用控制变量法逐个测试多因素综合算法里面的其他因素，并附测试截图。

**Comment by June19980** [comment]
按照时间顺序提交的作业，pending队列中越早提交的作业priority越高
![image](https://github.com/PKUHPC/Crane/assets/38131405/245a0aee-93ac-4246-bea7-f6691d24d879)

**Comment by Ashlee1994** [comment]
> 按照时间顺序提交的作业，pending队列中越早提交的作业priority越高 ![image](https://user-images.githubusercontent.com/38131405/252626159-245a0aee-93ac-4246-bea7-f6691d24d879.png)

截图有问题，多输出一些内容，最好把cqueue正常输入的内容都包含进来。其次，最终要的是，上图主要突出越早提交的作业优先级越高，那么作业是什么提交的这一列必须要列出来。

**Comment by June19980** [comment]
> 

![image](https://github.com/PKUHPC/Crane/assets/38131405/cb1886eb-0d0b-49a7-ad8b-0c67598769a4)

**Comment by June19980** [comment]
pending队列中，Test_Job和Test_Job01的唯一区别是前者mem为20M，后者mem为80M，所以后者优先级应该更低。如下图：
![image](https://github.com/PKUHPC/Crane/assets/38131405/0017f217-fe35-4ab0-9b45-debd5e4e61d7)

**Comment by Ashlee1994** [comment]
> 

这个截图方式非常好，还有一点需要修改的，就是cqueue默认将作业按照优先级从大到小排序，目前是按照作业号从大到小排序的

**Comment by June19980** [comment]
pending队列中，Test_Job和Test_Job01的唯一区别是前者cpu申请为2，后者为4，所以后者优先级应该更低，配置文件中age权重改为了0，提交时间不影响。如下图：
![image](https://github.com/PKUHPC/Crane/assets/38131405/98063354-aaec-4049-8f9e-2b2c98e0b3c3)

**Comment by June19980** [comment]
pending队列中，Test_Job和Test_Job01的唯一区别是前者node申请为1，后者为2，所以后者优先级应该更低，如下图：
![image](https://github.com/PKUHPC/Crane/assets/38131405/9a975a31-db2c-4720-b470-2bd8b6a47f2a)

**Comment by June19980** [comment]
在配置文件中将CPU的优先级设置为10，GPU为5，提交作业Test_Job和Test_Job01唯一区别是前者分区为CPU，后者为GPU，因此后者优先级更低
![image](https://github.com/PKUHPC/Crane/assets/38131405/519c480c-409b-4b5e-a268-ff75473cf761)
![image](https://github.com/PKUHPC/Crane/assets/38131405/7bbc9e11-7c49-4d9d-b96c-8bd2dc84daea)

**Comment by June19980** [comment]
创建三个不同qos如下图，提交三个作业，唯一区别是指定的qos不同，结果如图：![image](https://github.com/PKUHPC/Crane/assets/38131405/da1486db-93d0-4b17-8f35-3bb3227da9ae)
![image](https://github.com/PKUHPC/Crane/assets/38131405/c5303faf-ebda-46b3-9410-86ffb96c7512)

**Comment by June19980** [comment]
测试fairshare：创建两个账户下的用户，xj和CS，提交相同的作业脚本，running队列中xj作业更多，因此pending队列中CS优先级更高，如下图：
![image](https://github.com/PKUHPC/Crane/assets/38131405/854764f3-272e-4f70-a4ca-5cff217c86c5)
![image](https://github.com/PKUHPC/Crane/assets/38131405/d7389131-33e1-4243-8123-467ad51acb8c)
