### ISSUE TITLE
craned启动失败

### ISSUE THREAD

**Issue by s1015693563** [PKUHPC/CraneSched#184]
[root@crane01 bin]# ./craned 
Segmentation fault (core dumped)

![图片](https://github.com/PKUHPC/CraneSched/assets/51123047/b7a92610-4ea9-481f-90f1-f3b98c54f9c0)

**Comment by s1015693563** [comment]
操作系统为centos 7.9，内核版本3.10.0-1160.el7.x86_64

**Comment by RileyWen** [comment]
能提供stacktrace信息和具体执行的场景吗

**Comment by RileyWen** [comment]
或者能提供core文件吗
