### ISSUE TITLE
Question about scheduling performance

### ISSUE THREAD

**Issue by riccck** [PKUHPC/CraneSched#220]
CraneSched is an excellent project, and I have some questions to ask

1. The document states that CraneSched supports scheduling more than 10000 jobs per second. What is the reason why scheduling performance is faster than Slurm in terms of design?
2. Does CraneSched now support container based intelligent computing or is there a plan to support it？
3. Can CraneSched be integrated into k8s and utilize cloud native related ecosystems？

Thank you for your contributions, hope you can spare some time to help me.

**Comment by RileyWen** [comment]
1. The superior scheduling performance of CraneSched, when compared to Slurm, can be attributed to its distinct internal architecture, which is meticulously optimized for enhanced throughput. Our team is in the process of drafting a paper that will delve into the specifics of CraneSched's internal design to showcase its efficiency.
2. We are currently developing support for containers and have a preliminary demonstration showcasing a task running within a single-node container. However, refining this feature into a fully functional capability is anticipated to require substantial time.
3. We have designed a viable architectural framework that positions CraneSched to seamlessly function as both a container scheduler and executor. Our team is actively working on implementing this architecture to realize its potential.

**Comment by riccck** [comment]
@RileyWen  Thank you for your reply, I still have some questions here
> * We are currently developing support for containers and have a preliminary demonstration showcasing a task running within a single-node container. However, refining this feature into a fully functional capability is anticipated to require substantial time.

Where can I find this demonstration, or maybe it hasn't been released yet

> * We have designed a viable architectural framework that positions CraneSched to seamlessly function as both a container scheduler and executor. Our team is actively working on implementing this architecture to realize its potential.


Can I understand that CraneSched replaces some of the K8S default scheduler and kubelet features of K8S, rather than integrating with K8S non-invasive. If so, will the original workload of k8s (such as pod, deployment, etc.) in the integrated architecture still be scheduled using the default k8s scheduler?

**Comment by Nativu5** [comment]
Hi @riccck,

Thanks for reaching out. In response to your queries:

> Where can I find this demonstration, or maybe it hasn't been released yet

The container support is under actively development. A preliminary demo has been created, showcasing the ability to invoke runc/crun (or any OCI-compliant runtime) for initiating task within specified containers. Unfortunately, this demo isn't publicly available yet, but we are working to release it before the summer.

> Can I understand that CraneSched replaces some of the K8S default scheduler and kubelet features of K8S, rather than integrating with K8S non-invasive. If so, will the original workload of k8s (such as pod, deployment, etc.) in the integrated architecture still be scheduled using the default k8s scheduler?

Our system includes an independent container scheduler and executor, which operates separately from Kubernetes and does not intrude upon its functioning.

As mentioned by @RileyWen, we are writing a paper that details the technical specifications of CraneSched. Please stay tuned and look forward to your feedback.
