### ISSUE TITLE
Craned运行出错

### ISSUE THREAD

**Issue by Aurora211** [PKUHPC/CraneSched#257]
![Pic1](https://github.com/PKUHPC/CraneSched/assets/60863400/4e364530-dba3-4271-a2ea-a23701691471)  
如图所示，在运行Craned时出现无法初始化CPU和MEM的cgroups controller。请问这种如何修复。  

运行于Virtualbox虚拟机。
系统为：Ubuntu 22.04 LTS

**Comment by RileyWen** [comment]
需要以root身份运行craned

**Comment by Aurora211** [comment]
> 需要以root身份运行craned

感谢，我明天上班试试看

**Comment by RileyWen** [comment]
系统的cgroup都挂载了吗 我看所有的cgoup controller都不可用

**Comment by Aurora211** [comment]
> 系统的cgroup都挂载了吗 我看所有的cgoup controller都不可用

请问这个挂载是会自动挂载的吗？我看在说明文档中并未详细指出需要手动挂载，我好像并未操作任何有关Cgroup挂载的操作，请问应该挂载在哪，是否有办法手动挂载呢？谢谢
