### ISSUE TITLE
版本显示时需要加上 cranesched字段

### ISSUE THREAD

**Issue by Ashlee1994** [PKUHPC/CraneSched#374]
目前软件版本显示信息为： Version: 1.0.0+dev，需要改为 CraneSched v1.0.0 release
 
![Image](https://github.com/user-attachments/assets/7ed211e7-cf8f-40cd-a7ad-ad491119c446)

**Comment by Nativu5** [comment]
目前版本管理的策略是，如果是 release 的版本编译，version 没有后缀，如果是直接拉取开发分支上的源码编译，就会有 dev 后缀。
